"""added amount to sale

Revision ID: fc652107441a
Revises: 71ea4abdf655
Create Date: 2018-10-27 21:47:27.371514

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc652107441a'
down_revision = '71ea4abdf655'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sale', sa.Column('amount', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sale', 'amount')
    # ### end Alembic commands ###
